name: Auto Commit Every 10 Hours

on:
  schedule:
    - cron: "0 0,10,20 * * *"  # At 00:00, 10:00, and 20:00 UTC every day
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update timestamp file
        run: |
          echo "Updated on $(date)" > timestamp.txt

      - name: Commit changes
        run: |
          git config --global user.email "nilayjain12@gmail.com"
          git config --global user.name "Nilay Jain"
          git add timestamp.txt
          git commit -m "Auto update: $(date)" || echo "No changes to commit"

      - name: Push changes
        run: git push https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
